// Code generated by mockery v2.42.2. DO NOT EDIT.

package row

import mock "github.com/stretchr/testify/mock"

// MockRowI is an autogenerated mock type for the RowI type
type MockRowI struct {
	mock.Mock
}

// Scan provides a mock function with given fields: dest
func (_m *MockRowI) Scan(dest ...interface{}) error {
	var _ca []interface{}
	_ca = append(_ca, dest...)
	ret := _m.Called(_ca...)

	if len(ret) == 0 {
		panic("no return value specified for Scan")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(...interface{}) error); ok {
		r0 = rf(dest...)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewMockRowI creates a new instance of MockRowI. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRowI(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRowI {
	mock := &MockRowI{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
