name: Increment Version Tag on Push to Master

on:
  push:
    branches:
      - master

jobs:
  increment_tag:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git
        run: |
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"

      - name: Fetch all tags
        run: git fetch --tags

      - name: Get the latest tag
        id: get_latest_tag
        run: |
          # Check if there are any tags
          latest_tag=$(git tag -l --sort=-v:refname | head -n 1)
          echo "Latest tag: $latest_tag"
          if [ -z "$latest_tag" ]; then
            echo "No tags found. Setting initial tag to v0.0.0."
            latest_tag="v0.0.0"
          fi
          echo "::set-output name=latest_tag::$latest_tag"

      - name: Increment the tag
        id: increment_tag
        run: |
          latest_tag=${{ steps.get_latest_tag.outputs.latest_tag }}
          echo "Current latest tag is $latest_tag"
          
          # Split the latest tag into parts
          if [[ $latest_tag =~ ^v([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
            major=${BASH_REMATCH[1]}
            minor=${BASH_REMATCH[2]}
            patch=${BASH_REMATCH[3]}
            patch=$((patch+1))
            new_tag="v$major.$minor.$patch"
          else
            echo "The latest tag $latest_tag does not match the expected format v<major>.<minor>.<patch>"
            exit 1
          fi
          
          echo "New tag will be $new_tag"
          echo "::set-output name=new_tag::$new_tag"

      - name: Create and push new tag
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          new_tag=${{ steps.increment_tag.outputs.new_tag }}
          echo "Creating new tag $new_tag"
          git tag $new_tag
          git push origin $new_tag

      - name: Confirm tag creation
        run: |
          git fetch --tags
          git tag -l
